name: vm_log_api_dio
description: "Dio adapter for vm-log-api."
version: 2.0.0
repository: https://github.com/jhomlala/alice
homepage: https://github.com/jhomlala/alice
topics:
  - http
  - inspector
  - dio
  - interceptor
  - vm-log-api

environment:
  sdk: ">=3.7.0 <4.0.0"
  flutter: ">=3.29.0"

dependencies:
  vm_log_api: ^2.0.0
  dio: ^5.8.0+1
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^5.0.0

dependency_overrides:
  vm_log_api:
    path: ../vm_log_api
