name: vm_log_api_dio
description: "Dio adapter for vm-log-api."
version: 2.0.0
publish_to: none

topics:
  - http
  - inspector
  - dio
  - interceptor
  - vm-log-api

environment:
  sdk: ">=3.7.0 <4.0.0"
  flutter: ">=3.29.0"

dependencies:
  vm_log_api:
    git:
      url: https://bitbucket.vietmap.vn/scm/~datdnt/packages.git
      path: packages/vm-log-api/packages/vm_log_api
  dio: ^5.9.2
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^6.0.0

dependency_overrides:
  vm_log_api:
    path: ../vm_log_api
